# Generated by Django 3.1.5 on 2025-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
    ]
