# Generated by Django 3.1.5 on 2025-07-06 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_user_emailaddress'),
        ('resource_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VM_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_group_name', models.CharField(max_length=255)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_page.user')),
                ('vm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_dashboard.vms')),
            ],
        ),
    ]
