# Generated by Django 3.1.5 on 2025-07-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_user_emailaddress'),
        ('resource_dashboard', '0002_vm_group_vms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vms',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='project_name',
        ),
        migrations.AddField(
            model_name='vms',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resource_dashboard.projects'),
        ),
        migrations.AddField(
            model_name='vms',
            name='vm_ip',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='vms',
            name='vm_name',
            field=models.CharField(default='undefined_vm_name', max_length=255),
        ),
        migrations.AddField(
            model_name='vms',
            name='vm_online',
            field=models.CharField(default='undefined_vm_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='vms',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_page.user'),
        ),
    ]
