# Generated by Django 3.1.5 on 2025-07-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_dashboard', '0003_auto_20250707_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vms',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resource_dashboard.projects'),
        ),
    ]
