# Generated by Django 3.1.5 on 2025-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_dashboard', '0004_auto_20250707_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vms',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='VM_Group',
        ),
        migrations.DeleteModel(
            name='VMs',
        ),
    ]
