# Generated by Django 3.1.5 on 2025-07-07 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_user_emailaddress'),
        ('resource_dashboard', '0005_auto_20250707_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(default='undefined_vm_name', max_length=255)),
                ('vm_online', models.CharField(default='undefined_vm_name', max_length=255)),
                ('vm_ip', models.CharField(default='0.0.0.0', max_length=255)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_page.user')),
                ('project_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resource_dashboard.projects')),
            ],
        ),
        migrations.CreateModel(
            name='VM_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_group_name', models.CharField(max_length=255)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_page.user')),
                ('vm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_dashboard.vms')),
            ],
        ),
    ]
