# Generated by Django 3.1.5 on 2025-07-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_user_emailaddress'),
        ('resource_dashboard', '0006_vm_group_vms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='entity_id',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='entity_type',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login_page.user'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='vm_group',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login_page.user'),
        ),
        migrations.AlterField(
            model_name='vm_group',
            name='vm_group_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='vm_group',
            name='vm_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resource_dashboard.vms'),
        ),
        migrations.AlterField(
            model_name='vms',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login_page.user'),
        ),
    ]
