# Generated by Django 3.1.5 on 2025-07-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_dashboard', '0007_auto_20250707_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_group',
            name='vm_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resource_dashboard.projects'),
        ),
        migrations.DeleteModel(
            name='VMs',
        ),
    ]
