# Generated by Django 3.1.5 on 2025-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_dashboard', '0009_auto_20250707_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_identifier_code',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='vms',
            name='vm_online',
            field=models.CharField(default='offline', max_length=255),
        ),
    ]
