# Generated by Django 3.1.5 on 2025-07-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_user_emailaddress'),
        ('resource_dashboard', '0014_auto_20250716_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='owner_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_page.user'),
        ),
        migrations.AlterField(
            model_name='vm_group',
            name='owner_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_page.user'),
        ),
        migrations.AlterField(
            model_name='vm_group',
            name='vm_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_dashboard.vms'),
        ),
        migrations.AlterField(
            model_name='vms',
            name='owner_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_page.user'),
        ),
        migrations.AlterField(
            model_name='vms',
            name='project_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_dashboard.projects'),
        ),
    ]
