# Generated by Django 3.1.5 on 2025-06-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_auto_20250528_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailaddress',
            field=models.CharField(default='example@example.com', max_length=255),
        ),
    ]
